-- Run with: supabase db query --linked --file tests/legal-acceptance-rls.sql
-- All fixtures are rolled back, including the temporary auth users.
begin;

insert into auth.users (id) values
  ('b1b78196-578a-4e99-b43e-2671638c6083'),
  ('4d07ef58-5ce3-4668-af52-6a6c456a0cb3');

set local role authenticated;
select set_config('request.jwt.claim.sub', 'b1b78196-578a-4e99-b43e-2671638c6083', true);

insert into public.legal_acceptances (user_id, terms_version, privacy_version)
values (auth.uid(), 'test-terms', 'test-privacy')
on conflict (user_id, terms_version, privacy_version) do nothing;

-- The API retries with DO NOTHING, which must not need UPDATE privileges.
insert into public.legal_acceptances (user_id, terms_version, privacy_version)
values (auth.uid(), 'test-terms', 'test-privacy')
on conflict (user_id, terms_version, privacy_version) do nothing;

do $$
begin
  if (select count(*) from public.legal_acceptances) <> 1 then
    raise exception 'Own acceptance should be readable and idempotent';
  end if;
  if not exists (select 1 from public.legal_acceptances where accepted_at = now()) then
    raise exception 'Acceptance timestamp should be generated by the database';
  end if;
  begin
    insert into public.legal_acceptances (user_id, terms_version, privacy_version)
    values ('4d07ef58-5ce3-4668-af52-6a6c456a0cb3', 'test-terms', 'test-privacy');
    raise exception 'Writing another user acceptance must fail';
  exception when insufficient_privilege then null;
  end;
  begin
    update public.legal_acceptances set accepted_at = now();
    raise exception 'Updating acceptance must fail';
  exception when insufficient_privilege then null;
  end;
  begin
    insert into public.legal_acceptances (user_id, terms_version, privacy_version, accepted_at)
    values (auth.uid(), 'forged', 'forged', now() - interval '1 day');
    raise exception 'Supplying an acceptance timestamp must fail';
  exception when insufficient_privilege then null;
  end;
end $$;

select set_config('request.jwt.claim.sub', '4d07ef58-5ce3-4668-af52-6a6c456a0cb3', true);
do $$
begin
  if exists (select 1 from public.legal_acceptances) then
    raise exception 'Other users must not read the acceptance';
  end if;
end $$;

set local role anon;
do $$
begin
  begin
    perform 1 from public.legal_acceptances;
    raise exception 'Anonymous users must not read acceptances';
  exception when insufficient_privilege then null;
  end;
end $$;

rollback;
select 'Legal acceptance permission checks passed; all fixtures rolled back.' as result;
