create extension if not exists pgcrypto;
create type public.membership_role as enum ('owner','admin','member');
create type public.task_status as enum ('todo','in_progress','completed');
create type public.task_priority as enum ('na','low','medium','high');
create type public.task_origin as enum ('manual','ai');
create type public.document_status as enum ('uploading','processing','ready','failed');
create type public.proposal_status as enum ('proposed','approved','cancelled','failed');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.businesses (id uuid primary key default gen_random_uuid(), name text not null, legal_structure text, industry text, website text, location text, year_founded int, employee_count int, description text, products_services text, target_customers text, business_model text, organization text, current_goals text, current_challenges text, competitive_advantages text, annual_revenue text, fixed_costs text, variable_costs text, pricing_info text, budget_constraints text, financial_notes text, vector_store_id text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.business_memberships (business_id uuid not null references public.businesses(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,role membership_role not null default 'member',created_at timestamptz not null default now(),primary key(business_id,user_id));
create table public.conversations (id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,created_by uuid not null references auth.users(id),title text not null default 'New consultation',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.messages (id uuid primary key default gen_random_uuid(),conversation_id uuid not null references public.conversations(id) on delete cascade,business_id uuid not null references public.businesses(id) on delete cascade,role text not null check(role in('user','assistant')),content text not null,metadata jsonb,created_at timestamptz not null default now());
create table public.goals (id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,created_by uuid not null references auth.users(id),title text not null,description text,target_date date,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.task_folders (id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,created_by uuid not null references auth.users(id),name text not null,color text not null default '#64748B',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(business_id,name));
create table public.tasks (id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,created_by uuid not null references auth.users(id),goal_id uuid references public.goals(id) on delete set null,folder_id uuid references public.task_folders(id) on delete set null,title text not null,description text,due_date date,priority task_priority not null default 'na',status task_status not null default 'todo',color text,origin task_origin not null default 'manual',ai_action_request_id uuid,sort_order int not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.documents (id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,uploaded_by uuid not null references auth.users(id),name text not null,mime_type text not null,size_bytes bigint not null check(size_bytes>=0 and size_bytes<=15728640),storage_path text not null unique,status document_status not null default 'uploading',openai_file_id text,vector_store_id text,error_message text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.ai_action_requests (id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,conversation_id uuid references public.conversations(id) on delete set null,created_by uuid not null references auth.users(id),idempotency_key text not null,status proposal_status not null default 'proposed',payload jsonb not null,error_message text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(business_id,idempotency_key));
alter table public.tasks add constraint tasks_ai_request_fk foreign key(ai_action_request_id) references public.ai_action_requests(id) on delete set null;

create index memberships_user_idx on public.business_memberships(user_id,business_id);create index conversations_recent_idx on public.conversations(business_id,updated_at desc);create index messages_conversation_idx on public.messages(conversation_id,created_at);create index tasks_filter_idx on public.tasks(business_id,status,priority);create index tasks_due_idx on public.tasks(business_id,due_date) where due_date is not null;create index goals_business_idx on public.goals(business_id);create index folders_business_idx on public.task_folders(business_id);create index documents_business_idx on public.documents(business_id,status);

create function public.is_business_member(p_business_id uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.business_memberships where business_id=p_business_id and user_id=auth.uid())$$;
revoke all on function public.is_business_member(uuid) from public;grant execute on function public.is_business_member(uuid) to authenticated;
alter table public.profiles enable row level security;alter table public.businesses enable row level security;alter table public.business_memberships enable row level security;alter table public.conversations enable row level security;alter table public.messages enable row level security;alter table public.goals enable row level security;alter table public.task_folders enable row level security;alter table public.tasks enable row level security;alter table public.documents enable row level security;alter table public.ai_action_requests enable row level security;
create policy "profiles own" on public.profiles for all using(id=auth.uid()) with check(id=auth.uid());
create policy "members read businesses" on public.businesses for select using(public.is_business_member(id));create policy "members update businesses" on public.businesses for update using(public.is_business_member(id)) with check(public.is_business_member(id));
create policy "members read memberships" on public.business_memberships for select using(public.is_business_member(business_id));
do $$declare t text;begin foreach t in array array['conversations','messages','goals','task_folders','tasks','documents','ai_action_requests'] loop execute format('create policy "workspace select" on public.%I for select using(public.is_business_member(business_id))',t);execute format('create policy "workspace insert" on public.%I for insert with check(public.is_business_member(business_id))',t);execute format('create policy "workspace update" on public.%I for update using(public.is_business_member(business_id)) with check(public.is_business_member(business_id))',t);execute format('create policy "workspace delete" on public.%I for delete using(public.is_business_member(business_id))',t);end loop;end$$;

create function public.touch_updated_at() returns trigger language plpgsql as $$begin new.updated_at=now();return new;end$$;do $$declare t text;begin foreach t in array array['profiles','businesses','conversations','goals','task_folders','tasks','documents','ai_action_requests'] loop execute format('create trigger touch_updated_at before update on public.%I for each row execute function public.touch_updated_at()',t);end loop;end$$;
create function public.touch_conversation() returns trigger language plpgsql as $$begin update public.conversations set updated_at=now() where id=new.conversation_id;return new;end$$;create trigger messages_touch_conversation after insert on public.messages for each row execute function public.touch_conversation();

create function public.create_initial_workspace(p_user_id uuid,p_full_name text,p_business_name text) returns uuid language plpgsql security definer set search_path='' as $$declare b uuid;begin if auth.uid()<>p_user_id then raise exception 'not authorized';end if;if exists(select 1 from public.business_memberships where user_id=p_user_id) then raise exception 'workspace already exists';end if;insert into public.profiles(id,full_name) values(p_user_id,p_full_name) on conflict(id) do update set full_name=excluded.full_name;insert into public.businesses(name) values(p_business_name) returning id into b;insert into public.business_memberships(business_id,user_id,role) values(b,p_user_id,'owner');return b;end$$;
grant execute on function public.create_initial_workspace(uuid,text,text) to authenticated;

create function public.approve_task_plan(p_proposal_id uuid,p_business_id uuid,p_user_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare p public.ai_action_requests;g uuid;f uuid;t jsonb;count_created int:=0;begin if auth.uid()<>p_user_id or not public.is_business_member(p_business_id) then raise exception 'not authorized';end if;select * into p from public.ai_action_requests where id=p_proposal_id and business_id=p_business_id for update;if not found then raise exception 'proposal not found';end if;if p.status='approved' then return jsonb_build_object('already_approved',true);end if;if p.status<>'proposed' then raise exception 'proposal is not pending';end if;insert into public.goals(business_id,created_by,title,description,target_date) values(p_business_id,p_user_id,p.payload->'goal'->>'title',p.payload->'goal'->>'description',nullif(p.payload->'goal'->>'targetDate','')::date) returning id into g;if p.payload ? 'folder' then insert into public.task_folders(business_id,created_by,name,color) values(p_business_id,p_user_id,p.payload->'folder'->>'name',coalesce(p.payload->'folder'->>'color','#64748B')) on conflict(business_id,name) do update set color=excluded.color returning id into f;end if;for t in select * from jsonb_array_elements(p.payload->'tasks') loop insert into public.tasks(business_id,created_by,goal_id,folder_id,title,description,due_date,priority,color,origin,ai_action_request_id,sort_order) values(p_business_id,p_user_id,g,f,t->>'title',t->>'description',nullif(t->>'dueDate','')::date,(t->>'priority')::public.task_priority,t->>'color','ai',p.id,(t->>'order')::int);count_created:=count_created+1;end loop;update public.ai_action_requests set status='approved' where id=p.id;return jsonb_build_object('goal_id',g,'task_count',count_created);end$$;
grant execute on function public.approve_task_plan(uuid,uuid,uuid) to authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('business-documents','business-documents',false,15728640,array['application/pdf','text/plain','text/csv','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/vnd.openxmlformats-officedocument.wordprocessingml.document']) on conflict(id) do nothing;
create policy "workspace document read" on storage.objects for select using(bucket_id='business-documents' and public.is_business_member((storage.foldername(name))[1]::uuid));create policy "workspace document insert" on storage.objects for insert with check(bucket_id='business-documents' and public.is_business_member((storage.foldername(name))[1]::uuid));create policy "workspace document delete" on storage.objects for delete using(bucket_id='business-documents' and public.is_business_member((storage.foldername(name))[1]::uuid));
